/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */

export type RemoveDepartmentMembersReqDto = {
  /**
   * List of user IDs
   */
  userIds: Array<string>;
  /**
   *Organization code
   */
  organizationCode: string;
  /**
   * Department system ID (automatically generated by the GenAuth system and cannot be modified)
   */
  departmentId: string;
  /**
   * The type of department ID used in this call
   */
  departmentIdType?: RemoveDepartmentMembersReqDto.departmentIdType;
  /**
   * Tenant ID
   */
  tenantId?: string;
};

export namespace RemoveDepartmentMembersReqDto {
  /**
   * The type of department ID used in this call
   */
  export enum departmentIdType {
    DEPARTMENT_ID = "department_id",
    OPEN_DEPARTMENT_ID = "open_department_id",
    SYNC_RELATION = "sync_relation",
    CUSTOM_FIELD = "custom_field",
    CODE = "code",
  }
}
