/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */

export type RemoveTenantDepartmentMembersReqDto = {
  /**
   *Organization code
   */
  organizationCode: string;
  /**
   * Department system ID (automatically generated by the GenAuth system and cannot be modified)
   */
  departmentId: string;
  /**
   * The type of department ID used in this call
   */
  departmentIdType?: RemoveTenantDepartmentMembersReqDto.departmentIdType;
  /**
   * User ID at the associated user pool level
   */
  linkUserIds?: Array<string>;
  /**
   * Tenant member ID
   */
  memberIds?: Array<string>;
  /**
   * Tenant ID
   */
  tenantId?: string;
};

export namespace RemoveTenantDepartmentMembersReqDto {
  /**
   * The type of department ID used in this call
   */
  export enum departmentIdType {
    DEPARTMENT_ID = "department_id",
    OPEN_DEPARTMENT_ID = "open_department_id",
    SYNC_RELATION = "sync_relation",
    CUSTOM_FIELD = "custom_field",
    CODE = "code",
  }
}
